table dim_order_reviews
	lineageTag: 847a9d8a-3a31-4a8c-805c-66ed6faea734

	measure 'AVG Review Score' = SUM(dim_order_reviews[review_score]) / COUNT(dim_order_reviews[review_id])
		lineageTag: 5743ae96-19bb-4476-827d-efe6c6118d99

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column review_id
		dataType: string
		lineageTag: dabbedb7-9d37-4d4a-82bf-17d15abb181e
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 1ac08629-3250-4cda-93a7-2852a35a1008
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 5191d6e8-5ed1-46d4-99bf-9bfbb0fe5e04
		summarizeBy: none
		sourceColumn: review_score

		annotation SummarizationSetBy = User

	column review_comment_title
		dataType: string
		isHidden
		lineageTag: 59a2a4dd-5c87-45e4-b38e-457d3383ab58
		summarizeBy: none
		sourceColumn: review_comment_title

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		isHidden
		lineageTag: eb842725-1e3a-453e-9d92-dc054d2227a1
		summarizeBy: none
		sourceColumn: review_comment_message

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: bee56265-040f-4027-a362-ea1a50de2e4f
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: 551e86c7-1ad0-46cb-b2fa-428aac5f173f
			defaultHierarchy: LocalDateTable_8a2839e5-db97-4a1d-82f0-eb13f651a196.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column review_answer_timestamp
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 0cb50ad8-d054-4bdd-9c50-19e499172f82
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		variation Variation
			isDefault
			relationship: 4b3c6372-64c2-491b-aecd-6ad2de6bd017
			defaultHierarchy: LocalDateTable_ac4a9481-7f26-4153-ba5c-f8faa2725e18.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition dim_order_reviews = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Code\exeserce\DataViz\Brazilian E-Commerce\olist_order_reviews_dataset.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

